version: "3.4"
services:
  angular-chat:
    image: ${DOCKER_REGISTRY-}chatclient
    build: ./client
    ports:
      - "9000:80"
    environment: 
      - apiUrl=http://localhost:5000/api
      - baseUrl=http://localhost:5000

  signalr-api:
    image: ${DOCKER_REGISTRY-}chatapi
    build:
      context: ./server/ChatApi
    ports:
      - 5000:80
    environment: 
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Origins=http://localhost:9000
